name: 'Cisco Webex Teams Notify'
description: 'This action will send a notification to Cisco Webex Teams'
author: 'nozomi.nishinohara'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'