name: Build and Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "releases/v[0-9]+.[0-9]+.[0-9]+"


# Workflowsで使用する環境変数を定義
env:
  DOCKER_IMAGE: "ghcr.io/nozomi-nishinohara/actions-webex-notify"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: version
        if: startsWith(github.ref, 'refs/heads/release/v')
        run: |
          echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> "$GITHUB_ENV"
          echo "NUM_VERSION=${GITHUB_REF#refs/heads/release/v}" >> "$GITHUB_ENV"

      - name: version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          echo "NUM_VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: API Container Build and Push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ARG_VERSION=${{ env.NUM_VERSION }}
            ARG_REVISION=${{ github.sha }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          push: true
